import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import Banner from '../components/Banner/Banner'
import Features from '../components/Features/Features'
import Services from '../components/Services/Services'



const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,500,600,900,700|Arizonia" />
      </Head>
      <div className="app">
        <Banner/>
        <Features/>
        <Services/>
      </div>
    </div>
  )
}

export default Home
